import './favicon.png';
import './favicons/favicon-development.png';
import './favicons/favicon-staging.png';
import './favicons/favicon-recette.png';
import './favicons/favicon-review.png';
import './favicons/favicon-heroku.png';
import './danger_sign_blue.svg';
import './notice_people.svg';
import './search-no-result.svg';
import './checkbox.png';

import './sectors/default_sector.svg';
import './sectors/administration.svg';
import './sectors/agriculture.svg';
import './sectors/architecture.svg';
import './sectors/armee.svg';
import './sectors/art_design.svg';
import './sectors/arts_spectacle.svg';
import './sectors/artisanat.svg';
import './sectors/audiovisuel.svg';
import './sectors/automobile.svg';
import './sectors/banque.svg';
import './sectors/btp.svg';
import './sectors/commerce.svg';
import './sectors/communication.svg';
import './sectors/culture.svg';
import './sectors/droit.svg';
import './sectors/edition.svg';
import './sectors/electronique.svg';
import './sectors/gestion.svg';
import './sectors/energie.svg';
import './sectors/enseignement.svg';
import './sectors/environnement.svg';
import './sectors/filiere_bois.svg';
import './sectors/immobilier.svg';
import './sectors/industrie.svg';
import './sectors/industrie_alimentaire.svg';
import './sectors/informatique.svg';
import './sectors/hotellerie_restauration.svg';
import './sectors/marketing.svg';
import './sectors/mecanique.svg';
import './sectors/medical.svg';
import './sectors/mode.svg';
import './sectors/paramedical.svg';
import './sectors/securite.svg';
import './sectors/postal.svg';
import './sectors/social.svg';
import './sectors/sport.svg';
import './sectors/tourisme.svg';
import './sectors/transport.svg';

import './onboarding/confirm-desktop-2.svg';
import './onboarding/confirm-mobile-2.svg';

import './internship_offers_new/fast_time.svg';
import './internship_offers_new/paper.svg';

import './internship_applications/boy.svg';
import './internship_applications/girl.svg';

import './icons/noun_Handshake_2803586-1.svg';
import './icons/noun_job_offer_1461730-1.svg';
import './icons/noun_building_353052.svg';
import './icons/noun_Computer_2646597.svg';
import './icons/noun_group_Computeur_People.svg';
import './icons/noun_group_establishment.svg';
import './icons/noun_people_3139638.svg';
import './icons/arrow_right.svg';
import './icons/full_heart.svg';
import './icons/empty_heart.svg';
import './icons/disabled_heart.svg';
import './icons/file_copy_line.svg';

import './pages/statistics/hand_left.svg';
import './pages/statistics/hand_right.svg';
import './pages/statistics/handshake.svg';
import './pages/statistics/ok.svg';
import './pages/statistics/school.svg';

import './pages/teams/team.png';
import './pages/teams/team_icon_plus.svg';

import './pages/areas/space_girl.svg';
import './pages/areas/notification_icon.svg';

import './pages/invitations/email_icon.svg';
import './pages/invitations/person_icon.svg';

import './homepage/explications.svg';
import './homepage/back-to-top.svg';
import './homepage/01.svg';
import './homepage/02.svg';
import './homepage/03.svg';
import './homepage/04.svg';
import './homepage/contract.svg';
import './homepage/dl_resource.png';
import './homepage/france.svg';
import './homepage/dashboard.svg';
import './homepage/logo-education-nationale.svg';
import './homepage/backgrd-header.webp';
import './homepage/backgrd-header.png';
import './homepage/hero-side-stamp.png';
import './homepage/eleves_card_illustration.jpg';
import './homepage/pro_card_illustration.jpg';
import './homepage/education_card_illustration.jpg';
import './homepage/onisep.png';
import './homepage/eleves_hero_illustration.png';

import './homepage/resources/etablissements.svg';
import './homepage/resources/parents_eleves.svg';
import './homepage/resources/professionnels.svg';
import './homepage/resources/referents.svg';

import './homepage/hero-illustration.svg';
import './homepage/opportunities-illustration.svg';
import './homepage/ms3e-big-badge.svg';
import './homepage/accompagner-vos-eleves.svg';
import './homepage/trouver-un-stage.svg';
import './homepage/metiers.svg';
import './homepage/school-management.svg';
import './homepage/accueillir-un-stagiaire.svg';
import './homepage/link-step-1-2.svg';
import './homepage/link-step-2-3.svg';

import  './homepage/everyone/ms2e-stamp-medium.png'
import  './homepage/students/spin-vector.svg'

import './homepage/partenaires/involved_companies/afep.png'
import './homepage/partenaires/involved_companies/airbus.png'
import './homepage/partenaires/involved_companies/bnp.png'
import './homepage/partenaires/involved_companies/bouygues.png'
import './homepage/partenaires/involved_companies/bpce.png'
import './homepage/partenaires/involved_companies/ca.png'
import './homepage/partenaires/involved_companies/carrefour.png'
import './homepage/partenaires/involved_companies/creditmutuel.png'
import './homepage/partenaires/involved_companies/croixrouge.png'
import './homepage/partenaires/involved_companies/decathlon.png'
import './homepage/partenaires/involved_companies/disneyland.png'
import './homepage/partenaires/involved_companies/engie.png'
import './homepage/partenaires/involved_companies/fnacdarty.png'
import './homepage/partenaires/involved_companies/francetravail.png'
import './homepage/partenaires/involved_companies/intermarche.png'
import './homepage/partenaires/involved_companies/laposte.png'
import './homepage/partenaires/involved_companies/limoges.png'
import './homepage/partenaires/involved_companies/loreal.png'
import './homepage/partenaires/involved_companies/lyon.png'
import './homepage/partenaires/involved_companies/meae.png'
import './homepage/partenaires/involved_companies/medef.png'
import './homepage/partenaires/involved_companies/myfuture.png'
import './homepage/partenaires/involved_companies/pau.png'
import './homepage/partenaires/involved_companies/ritz.png'
import './homepage/partenaires/involved_companies/safran.png'
import './homepage/partenaires/involved_companies/sncf.png'
import './homepage/partenaires/involved_companies/sonepar.png'
import './homepage/partenaires/involved_companies/strasbourg.png'
import './homepage/partenaires/involved_companies/thales.png'
import './homepage/partenaires/auvergne.png'
import './homepage/partenaires/bourgogne.png'
import './homepage/partenaires/bretagne.png'
import './homepage/partenaires/centrevaldeloire.png'
import './homepage/partenaires/corse.png'
import './homepage/partenaires/grandest.png'
import './homepage/partenaires/guadeloupe.png'
import './homepage/partenaires/guyane.png'
import './homepage/partenaires/hautsdefrance.png'
import './homepage/partenaires/iledefrance.png'
import './homepage/partenaires/martinique.png'
import './homepage/partenaires/mayotte.png'
import './homepage/partenaires/normandie.png'
import './homepage/partenaires/nouvelleaquitaine.png'
import './homepage/partenaires/occitanie.png'
import './homepage/partenaires/onisep.png'
import './homepage/partenaires/paysdeloire.png'
import './homepage/partenaires/paca.png'
import './homepage/partenaires/reunion.png'


import './homepage/sponsors/logo-ministere-education-nationale.svg';
import './homepage/sponsors/logo-ministere-de-la-transition-ecologique.svg';

import './documents_utiles/CarnetStagePro_USEA_WEB-2.jpg';
import './documents_utiles/RienNeSertDeCourirPageBD.jpg';
import './documents_utiles/MS3_Programme-a-remplir.jpg';
import './documents_utiles/USEA-Carnet-Stage-Education.jpg';
import './documents_utiles/USEA-Cherchez-la-chercheuse.jpg';
import './documents_utiles/carnet-de-stage-pro.jpg';
import './documents_utiles/versLinfini.jpg';
import './documents_utiles/eleves.jpg';
import './documents_utiles/equipe-pedago.jpg';
import './documents_utiles/offreurs.jpg';
import './documents_utiles/partenaires.jpg';
import './documents_utiles/referents.jpg';


import './modes_d_emploi/miniature-MS3_Mode-d-emploi-eleves.jpg';
import './modes_d_emploi/miniature-MS3_Mode-d-emploi-entreprises.jpg';
import './modes_d_emploi/miniature-MS3_Mode-d-emploi-membres-pedagogique.jpg';
import './modes_d_emploi/miniature-MS3_Mode-d-emploi-referents-departementaux.jpg';
import './modes_d_emploi/miniature-MS3_Mode-d-emploi-global-2022.jpg';
